config/routes.rb
Rails.application.routes.draw do


  resources :messages
  resources :users 
  resources :mentees, controller: 'users', type: 'Mentee' 
  
  resources :mentors, controller: 'users', type: 'Mentor' do 
    resources :mentorships, only: [:new, :create, :destroy, :update]
  end

  resources :user_questions, only: [:new, :create, :destroy, :update]
  resource :session, only: [:new, :create, :destroy]

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/users/current', to: 'users#current'
  get '/homepage', to: 'users#homepage'

  root 'static#index'

end

app/models/users/mentee.rb
class Mentee < User
	has_many :mentorships
	has_many :mentors, through: :mentorships
  has_many :messages, dependent: :destroy
	has_many :mentors, -> { where confirmed: true }, class_name: 'Mentorship'
	has_many :pending_requests, -> { where confirmed: false }, class_name: 'Mentorship'
end

app/models/users/mentor.rb
class Mentor < User
	has_many :mentorships
	has_many :mentees, through: :mentorships
  has_many :messages, dependent: :destroy
	has_many :mentees, -> { where confirmed: true }, class_name: 'Mentorship'
	has_many :pending_requests, -> { where confirmed: false }, class_name: 'Mentorship'
end

app/models/users/user.rb
class User < ActiveRecord::Base
	has_secure_password
  has_many :user_questions
  has_many :questions, through: :user_questions, dependent: :destroy
  scope :mentors, -> { where(type:'Mentor') }
  scope :mentees, -> { where(type:'Mentee') }

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment :avatar, :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }

	validates :first_name, :last_name, :email, presence: true

  def current
    respond_to do |format|
      format.json { render json: {
          id: current_user.id,
          type: current_user.type,
          email: current_user.email,
          first_name: current_user.first_name
        }
      }
    end
  end

  def homepage
    respond_to do |format|
      format.json { render json: {
          id: current_user.id,
          email: current_user.email,
          first_name: current_user.first_name
        }
      }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.where(type: params[:type])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.where(type: params[:type]).find(params[:id])
  end

  # GET /hompage
  def homepage
    @userquestion = UserQuestion.all

    rand_id = rand(Question.count)
    @question = Question.where("id >= ?", rand_id).first
  end

  # GET /users/new
  def new
    @user = User.new
    @user.type = params[:type]
  end

  # GET /users/1/edit
  def edit
    @user = User.new
    @user.type = params[:type]
  end

  # POST /users
  # POST /users.json
  def create
    if params[:user][:type] == 'Mentor'
      @mentor = Mentor.new(user_params)
      respond_to do |format|
        if @mentor.save
          login!(@mentor)
          format.html { redirect_to @mentor, notice: 'Mentor was successfully created.' }
          format.json { render :show, status: :created, location: @mentor }
        else
          format.html { render :new }
          format.json { render json: @mentor.errors, status: :unprocessable_entity }
        end
      end
    elsif params[:user][:type] == 'Mentee'
      @mentee = Mentee.new(user_params)
      respond_to do |format|
        if @mentee.save
          login!(@mentee)
          format.html { redirect_to @mentee, notice: 'Mentee was successfully created.' }
          format.json { render :show, status: :created, location: @mentee }
        else
          format.html { render :new }
          format.json { render json: @mentee.errors, status: :unprocessable_entity }
        end
      end
    else
      render :text => 'Oops something went wrong! Please try again.'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if params[:mentor]
      respond_to do |format|
        if current_user.update(mentor_params)
          format.html { redirect_to homepage_path, notice: 'Edits saved.' }
          format.json { render :show, status: :ok, location: @mentor }
        else
          format.html { render :edit }
          format.json { render json: @mentor.errors, status: :unprocessable_entity }
        end
      end
    elsif params[:mentee]
      respond_to do |format|
        if current_user.update(mentee_params)
          format.html { redirect_to homepage_path, notice: 'Edits saved.' }
          format.json { render :show, status: :ok, location: @mentee }
        else
          format.html { render :edit }
          format.json { render json: @mentee.errors, status: :unprocessable_entity }
        end
      end
    else
      render :text => 'Oops something went wrong! Please try again.'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.type = params[:type]
    @user.destroy
    logout!(@user)
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = Mentee.find(params[:id]) || Mentor.find(params[:id])
  end

  # Only these parameters can be passed through the form
  def user_params
    params.require(:user).permit(:type, :first_name, :last_name, :email, :location, :current_job, :industry, :quote, :fun_fact, :site, :avatar, :password, :password_confirmation)
  end

  def mentee_params
    params.require(:mentee).permit(:type, :first_name, :last_name, :email, :location, :current_job, :industry, :quote, :fun_fact, :site, :avatar, :password, :password_confirmation)
  end

  def mentor_params
    params.require(:mentor).permit(:type, :first_name, :last_name, :email, :location, :current_job, :industry, :quote, :fun_fact, :site, :avatar, :password, :password_confirmation)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def user_is_current_user
    user = User.find(params[:id])

    if current_user
      redirect_to user_path(current_user) unless user == current_user
    else
      redirect_to new_session_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

	# def is_current_user?
	# 	@user.type
	# end
end

app/views/users/mentees/_home.html.erb
<div class="row">
	<%= link_to 'Edit Profile', edit_mentee_path(current_user), class: "btn btn-default" %>
	<%= link_to 'View My Profile', mentee_path(current_user), class: "btn btn-default" %>
</div>

<span id="userType"><%=current_user.type%></span>

<div class="row">
<div class="col-sm-6 pending-mentors">
<h2>Pending Mentorship Requests</h2>
<div class="pending mentorships">
	<% if current_user.pending_requests.any? %>
		<% current_user.pending_requests.each do |mentor| %>
			<h3><a href="mentors/<%= mentor.mentor.id %>"><%= mentor.mentor.first_name %> <%= mentor.mentor.last_name %></a></h3>
			<h4><%= mentor.mentor.industry %></h4>
			<p class="italic">Request sent at <%= mentor.created_at.strftime('%l:%M%P on %B %d, %Y') %></p>
		<% end %>
	<% else %>
		<p class="italic">You currently have no pending mentorship requests.</p>
	<% end %>
</div>
</div>

<div class="col-sm-12 mentorships-header">
	<h1>Current Mentors</h1>
	<p class="quote"> Connect with your mentors below! </p>
</div>


<% if current_user.mentors.any? %>
	<% current_user.mentors.each do |mentor| %>
<div class="col-sm-6 current-mentors">
<div class="current mentorships">
			<button class="btn btn-default" id="end-mentorship">End Mentorship</button>
			<h3><a href="mentors/<%= mentor.mentor.id %>"><%= mentor.mentor.first_name %> <%= mentor.mentor.last_name %></a></h3>
			<p><%= mentor.mentor.industry %></p>
			<p class="italic small">Mentor since <%= mentor.created_at.strftime('%a %B %d %Y') %></p>

			<div class="inbox" id="inbox_<%= mentor.mentor.id %>">
				<ul class="conversation" id="conversation_<%=mentor.mentor.id%>">

				</ul>
			</div>

			<button data-method="compose" class="get-message btn btn-default">Message <%= mentor.mentor.first_name %></button>
			<form class="compose" id="form_<%= mentor.mentor.id %>">
				<div class="close-window">&times;</div>
			  <input type="hidden" name="mentee_id" value="<%= current_user.id %>">
			  <input type="hidden" name="mentor_id" value="<%= mentor.mentor.id %>">
			  <input type="text" name="subject" placeholder="Subject" class="form-control">
			  <textarea name="content" placeholder="Message" class="form-control"></textarea>
			  <button class="btn btn-default send-message" id="send_<%=mentor.mentor.id%>">Send</button>
			</form>
		</div>
	</div>
	<% end %>
<% else %>
<div class="col-sm-12 current-mentors">
	<div class="current mentorships">
				<p class="italic">You have no current mentors</p>
			</div>
	</div>
<% end %>
</div>